:- include('solver_1_0.pl').

solverVersion("OLD").

isSolutionAndWrite(Board,N,Seed, OutputFile, Verbose, Solution):-
    (Verbose = 1, writeln("PROLOG: Solving..."); true),
    call_time(
        isSolution(Board,Solution),
        TimeDict
    ),
    solverVersion(Version),
    string_concat("Solved by: v", Version, Comment),
    translateToBoardWithBlackLetter(Board, Solution, SolutionInGenericFormat), 


    writeSolution(OutputFile, N,Seed, Comment, SolutionInGenericFormat, TimeDict),

    %Print some info to the console so you can see live what is happening:
    (Verbose = 1,
        write("Solved! Took "),
        write(TimeDict.cpu),
        write(" seconds, "),
        write(TimeDict.inferences),
        writeln(" inferences"),
        maplist(writeln, SolutionInGenericFormat),
        writeln(""),
        writeln(Solution);
        true
    ).


writeSolution(Filename, N, Seed, Comment, SolutionInGenericFormat, TimeDict) :-
    open(Filename, write, File),
    writeln(File, N),
    writeln(File, ""),
    loop_through_list(File, SolutionInGenericFormat),
    writeln(File, ""),
    writeln(File, Seed),
    writeln(File, Comment),
    write(File, "#prologTime="),
    writeln(File, TimeDict.cpu),
    write(File, "#prologInferences="),
    writeln(File, TimeDict.inferences),
    close(File).



%Writing board with chosen zeros to solution output file
%%%%%%%%%%%%
translateToBoardWithBlackLetter(Board, SolutionMatrix, SolutionInGenericFormat):-
    sameShape2(Board, SolutionInGenericFormat),
    allPositionsWithValue2(Board, Positions),
    maplist(translateToBoardValueOrBoardBlack(SolutionInGenericFormat, SolutionMatrix), Positions).

translateToBoardValueOrBoardBlack(Solution,SolutionMatrix,(X,Y,V)):-
    elementAt2(Solution, X, Y, SolutionValue),
    boardValueOrBlackedBoardValue((X,Y,V),SolutionMatrix, SolutionValue).

boardValueOrBlackedBoardValue((X,Y,V), SolutionMatrix, Res) :- 
    elementAt2(SolutionMatrix, X,Y, 0), 
    string_concat(V,"B", Res), !.

boardValueOrBlackedBoardValue((_,_,V), _, V).


% gives you the indices as pairs (X,Y) that have a nonzero value at the board
allPositionsWithValue2(Board, PositionsWithValue) :-
    findall( (X,Y,V), elementAt2(Board,X,Y,V), PositionsWithValue).


%Writes a matrix to a file
% (GENERATED BY CHATGPT )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
loop_through_list(_File, []) :- !.
loop_through_list(File, [Row|Rows]) :-
    write_row(File, Row),
    nl(File),
    loop_through_list(File, Rows).

write_row(_File, []).
write_row(File, [H|T]) :-
    write(File, H),
    write_row_rest(File, T).

write_row_rest(_File, []).
write_row_rest(File, [H|T]) :-
    write(File, ' '),
    write(File, H),
    write_row_rest(File, T).
%%%%%%


%get from board at X,Y. Top Left is 0,0.
elementAt2(Board, X,Y,Element):-
    getRow2(Board,Y,Row), 
    % row is now the entire row, get the element from that:
    nth0(X,Row,Element).

getRow2(Board, X, Row):- nth0(X,Board,Row).

sameShape2([], []).
sameShape2([A|As], [B|Bs]) :-
    same_length(A, B),
    sameShape2(As, Bs).





