isSolutionAndWrite(Board,N,Seed, OutputFile, SolutionBoard, SolutionZerod):-
    call_time(
        isSolutionZerodPositions(Board, SolutionBoard, SolutionZerod ),
        TimeDict
    ),
    solverVersion(Version),
    string_concat("Solved by: v", Version, Comment),
    writeSolution(OutputFile, N,Seed, Comment, Board, SolutionZerod,TimeDict),
    %Print some info to the console so you can see live what is happening:
    write("Solved! Took "),
    write(TimeDict.cpu),
    write(" seconds, "),
    write(TimeDict.inferences),
    writeln(" inferences").


%Writing board with chosen zeros to solution output file
%%%%%%%%%%%%
translateToBoardWithBlackLetter(Board, Zerod, SolutionInGenericFormat):-
    sameShape(Board, SolutionInGenericFormat),
    allPositionsWithValue(Board, Positions),
    maplist(translateToBoardValueOrBoardBlack(SolutionInGenericFormat, Zerod), Positions).

translateToBoardValueOrBoardBlack(Solution,Zerod,(X,Y,V)):-
    elementAt(Solution, X, Y, SolutionValue),
    boardValueOrBlackedBoardValue((X,Y,V),Zerod, SolutionValue).

boardValueOrBlackedBoardValue((X,Y,V), Zerod, Res) :- ord_memberchk((X,Y), Zerod), string_concat(V,"B", Res), !.

boardValueOrBlackedBoardValue((_,_,V), _, V).



writeSolution(Filename, N, Seed, Comment, Board, Zerod,TimeDict) :-
    translateToBoardWithBlackLetter(Board,Zerod, SolutionMatrix), 
    open(Filename, write, File),
    writeln(File, N),
    writeln(File, ""),
    loop_through_list(File, SolutionMatrix),
    writeln(File, ""),
    writeln(File, Seed),
    writeln(File, Comment),
    write(File, "#prologTime="),
    writeln(File, TimeDict.cpu),
    write(File, "#prologInferences="),
    writeln(File, TimeDict.inferences),
    close(File).




%Writes a matrix to a file
% (GENERATED BY CHATGPT )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
loop_through_list(_File, []) :- !.
loop_through_list(File, [Row|Rows]) :-
    write_row(File, Row),
    nl(File),
    loop_through_list(File, Rows).

write_row(_File, []).
write_row(File, [H|T]) :-
    write(File, H),
    write_row_rest(File, T).

write_row_rest(_File, []).
write_row_rest(File, [H|T]) :-
    write(File, ' '),
    write(File, H),
    write_row_rest(File, T).
%%%%%%

