%%%%%%%%%%%%%%%%%%%%%
%Utils
%%%%%%%%%%%%%5

%For translating a set of chosen duplicates to a board (list of rows).
%%%%%%%%%%%%
translateToBoard(Board, Zerod, Solution):-
    sameShape(Board, Solution),
    allPositionsWithValue(Board, Positions),
    maplist(translatePositionToBoardValue(Solution, Zerod), Positions).

translatePositionToBoardValue(Solution,Zerod,(X,Y,V)):-
    elementAt(Solution, X, Y, SolutionValue),
    boardValueOrZerod((X,Y,V),Zerod, SolutionValue).


boardValueOrZerod((X,Y,_), Zerod, 0) :- ord_memberchk((X,Y), Zerod), !.
boardValueOrZerod((_,_,V), _, V).

sameShape([], []).
sameShape([A|As], [B|Bs]) :-
    same_length(A, B),
    sameShape(As, Bs).



%Writes a matrix to a file
% (GENERATED BY CHATGPT )
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
loop_through_list(_File, []) :- !.
loop_through_list(File, [Row|Rows]) :-
    write_row(File, Row),
    nl(File),
    loop_through_list(File, Rows).

write_row(_File, []).
write_row(File, [H|T]) :-
    write(File, H),
    write_row_rest(File, T).

write_row_rest(_File, []).
write_row_rest(File, [H|T]) :-
    write(File, ' '),
    write(File, H),
    write_row_rest(File, T).
%%%%%%

writeSolution(Filename, N, Seed, Comment, Board, Zerod,TimeDict) :-
    translateToBoardWithBlackLetter(Board,Zerod, SolutionMatrix), 
    open(Filename, write, File),
    writeln(File, N),
    writeln(File, ""),
    loop_through_list(File, SolutionMatrix),
    writeln(File, ""),
    writeln(File, Seed),
    writeln(File, Comment),
    write(File, "#prologTime="),
    writeln(File, TimeDict.cpu),
    write(File, "#prologInferences="),
    writeln(File, TimeDict.inferences),
    close(File),
    write("Wrote puzzle solution to "),
    print(Filename),
    writeln("").



%Writing board with chosen zeros to solution output file
%%%%%%%%%%%%

translateToBoardWithBlackLetter(Board, Zerod, SolutionInGenericFormat):-
    sameShape(Board, SolutionInGenericFormat),
    allPositionsWithValue(Board, Positions),
    maplist(translateToBoardValueOrBoardBlack(SolutionInGenericFormat, Zerod), Positions).

translateToBoardValueOrBoardBlack(Solution,Zerod,(X,Y,V)):-
    elementAt(Solution, X, Y, SolutionValue),
    boardValueOrBlackedBoardValue((X,Y,V),Zerod, SolutionValue).

boardValueOrBlackedBoardValue((X,Y,V), Zerod, Res) :- ord_memberchk((X,Y), Zerod), string_concat(V,"B", Res), !.

boardValueOrBlackedBoardValue((_,_,V), _, V).





